### ISSUE TITLE
 tf.math.reduce_mean(kernel, axis=[0, 1, 2], 

### ISSUE THREAD

**Issue by henbucuoshanghai** [joe-siyuan-qiao/WeightStandardization#15]
in tensorflow  ,the kernel's  shape is c,k,k                   axis=[0, 1, 2]??
0  means channel of input?   1 and 2 means the h and width of kernel?

**Comment by csrhddlam** [comment]
According to [TF doc](https://www.tensorflow.org/api_docs/python/tf/nn/conv2d), the kernel shape of conv2d is [h, w, in, out]. WS is standardizing (reducing) over [h, w, in] axes.

**Comment by henbucuoshanghai** [comment]
thks
