### ISSUE TITLE
AttributeError: 'module' object has no attribute 'reduce_mean'

### ISSUE THREAD

**Issue by longmalongma** [joe-siyuan-qiao/WeightStandardization#17]
hello,thanks for your work,i meet this proble.
 kernel_mean = tf.math.reduce_mean(kernel, axis=[0, 1, 2], keepdims=True, name='kernel_mean')
AttributeError: 'module' object has no attribute 'reduce_mean'
do you know why?

**Comment by csrhddlam** [comment]
Thanks for your interest. Recent official tensorflow releases seem to have tf.math.reduce_mean (r1.15, r1.14, tf2.0). Are you using older version of tensorflow? You could try tf.reduce_mean or search "reduce_mean" in the doc of your tensorflow version.

**Comment by longmalongma** [comment]
Thank you for your reply,i have got it,do you publish pytorch codes?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Huiyu Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月8日(星期天) 凌晨0:21
收件人:&nbsp;"joe-siyuan-qiao/WeightStandardization"<WeightStandardization@noreply.github.com&gt;;
抄送:&nbsp;"longma"<1442342449@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [joe-siyuan-qiao/WeightStandardization] AttributeError: 'module' object has no attribute 'reduce_mean' (#17)




Thanks for your interest. Recent official tensorflow releases seem to have tf.math.reduce_mean (r1.15, r1.14, tf2.0). Are you using older version of tensorflow? You could try tf.reduce_mean or search "reduce_mean" in the doc of your tensorflow version.

**Comment by csrhddlam** [comment]
Yes, this repo contains our PyTorch code for classification, detection, and segmentation.

**Comment by longmalongma** [comment]
> Yes, this repo contains our PyTorch code for classification, detection, and segmentation.

Thank you very much
