### ISSUE TITLE
In my test,gn+ws result is worse

### ISSUE THREAD

**Issue by hust-kevin** [joe-siyuan-qiao/WeightStandardization#3]
I train gn and gn+ws on pascal voc ,all the config include batchsize,lr,network is same,but the result of gn+ws is more worse. PS: I use mmdetection

| Backbone                          | AP     | AP50    | AP75    |
|:---------------------------------:|:------:|:-------:|:-------:|
| `Faster-rcnn:R-50-FPN(gn) `       | 0.484  | 0.794   | 0.519   | 
| `Faster-rcnn:R-50-FPN(gn+ws) `    | 0.470  | 0.780   | 0.491   |

**Comment by csrhddlam** [comment]
Did you successfully transfer our ws pretrained model to mmdetection?

**Comment by hust-kevin** [comment]
sorry, it's  my fault, I just use the gn pretrained model,
I try to transfer ws pretrained model to mmdetection, but failed
