### ISSUE TITLE
About pretrained model R101-GN-WS

### ISSUE THREAD

**Issue by JrPeng** [joe-siyuan-qiao/WeightStandardization#7]
It seems that the model downloaded from http://cs.jhu.edu/~syqiao/WeightStandardization/X-101-GN-WS.pth.tar is broken. Could you check the file? Thank you.

**Comment by joe-siyuan-qiao** [comment]
Thanks for your interest in WS. Could you please provide more details about what happened to you when downloading that file? I just tried to download and open it, and it seemed ok to me. Thanks.

**Comment by JrPeng** [comment]
When I tried to open as follow:
`tar -xvf X-101-GN-WS.pth.tar`
I was told that it seems not a tar file. Thank you for your reply.

**Comment by joe-siyuan-qiao** [comment]
I see. Sorry for the confusion. Please use torch.load from PyTorch to load the file.

**Comment by JrPeng** [comment]
Thank you!
